Repository SOPT-31th-Seminar-10/iOS-Welaaa, pull requests merged in 2022-11, with the labels that each got.

#4 [#3] SearchUI 구현
  .gitignore
  IN_SOPT_Welaaa/IN_SOPT_Welaaa.xcodeproj/project.pbxproj
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Data/Name.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Common/BaseView.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Common/BaseViewController.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/Cell/CategoryCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/Cell/KeywordCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/Cell/SearchWordCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/SearchSection.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/LeftAlignedCollectionViewFlowLayout.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/NavigationView.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/PopularView.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/SearchSectionView.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/SearchView.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/SearchViewController.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/ViewController/SearchViewController.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/bookImage.imageset/Contents.json
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/bookImage.imageset/IMG_2971.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/bookImage.imageset/IMG_2971@2x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/bookImage.imageset/IMG_2971@3x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/indicator.imageset/Contents.json
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/indicator.imageset/indicator.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/indicator.imageset/indicator@2x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/indicator.imageset/indicator@3x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/searchRank.imageset/Contents.json
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/searchRank.imageset/ios_search_rank.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/searchRank.imageset/ios_search_rank@2x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/searchRank.imageset/ios_search_rank@3x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Util/Constant/Image.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Util/Extension/UITextField + Extension.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Util/Extension/UIView + Extension.swift
Labels: Style, 승찬💕

#11 [#7] 네트워크 세팅 및 SearchView 연결
  IN_SOPT_Welaaa/IN_SOPT_Welaaa.xcodeproj/project.pbxproj
  IN_SOPT_Welaaa/IN_SOPT_Welaaa.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Data/Search/Category.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Network/GenericResponse.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Network/NetworkResult.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Network/Search/CategoryAPI.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Network/Search/CategoryService.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/Cell/CategoryCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/View/SearchView.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Search/ViewController/SearchViewController.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Info.plist
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Util/Constant/URLs.swift
Labels: Add, Feat, Network, 승찬💕

#10 [#8] 내 서랍 뷰 UI 구현 완료!
  IN_SOPT_Welaaa/IN_SOPT_Welaaa.xcodeproj/project.pbxproj
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/Cell/BookCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/Cell/RecordCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/Cell/ShelfCategoryCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/Model/FetchBookListResponseDto.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/View/ShelfViewController.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/ic_profile.imageset/Contents.json
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/ic_profile.imageset/Ellipse 1.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/ic_profile.imageset/Ellipse 1@2x.png
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Resource/Image.xcassets/ic_profile.imageset/Ellipse 1@3x.png
Labels: Feat, 가연💕

#18 [#17] 내 서랍 UI 구현
  IN_SOPT_Welaaa/IN_SOPT_Welaaa.xcodeproj/project.pbxproj
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/BookCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/FetchBookListResponseDto.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/RecordCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/ShelfCategoryCollectionViewCell.swift
  IN_SOPT_Welaaa/IN_SOPT_Welaaa/Presentation/Shelf/View/ShelfViewController.swift
Labels: Style, 승찬💕
